services:
  - type: web
    name: monteiro-lite
    env: python
    plan: free
    buildCommand: pip install .
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true